<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="360LP042" name="com.edureka.registration.VerifySubjectLineOfVerification" tests="5" failures="1" timestamp="26 Jul 2016 12:09:27 GMT" time="50.593" errors="4">
  <testcase name="test_025VerifySubjectLineOfVerification" time="50.593" classname="com.edureka.registration.VerifySubjectLineOfVerification">
    <failure type="java.lang.AssertionError" message="Element Locator ://div[contains(text(),&#039;is your verification code for secure access&#039;)] Not found expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Element Locator ://div[contains(text(),'is your verification code for secure access')] Not found expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.edureka.util.DriverHelper.clickOn(DriverHelper.java:311)
	at com.edureka.pages.Mailnator.openMail(Mailnator.java:52)
	at com.edureka.registration.VerifySubjectLineOfVerification.test_025VerifySubjectLineOfVerification(VerifySubjectLineOfVerification.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- test_025VerifySubjectLineOfVerification -->
  <testcase name="test_029VerifyNewPasswordShouldNotBeLessThan8Characters" time="0.000" classname="com.edureka.registration.VerifySubjectLineOfVerification">
    <error type="java.lang.Throwable" message="Method VerifySubjectLineOfVerification.test_029VerifyNewPasswordShouldNotBeLessThan8Characters()[pri:0, instance:com.edureka.registration.VerifySubjectLineOfVerification@e45f292] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method VerifySubjectLineOfVerification.test_029VerifyNewPasswordShouldNotBeLessThan8Characters()[pri:0, instance:com.edureka.registration.VerifySubjectLineOfVerification@e45f292] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </error>
  </testcase> <!-- test_029VerifyNewPasswordShouldNotBeLessThan8Characters -->
  <testcase name="test_027VerifyErrorMsgForIncorrectVeirficationCode" time="0.000" classname="com.edureka.registration.VerifySubjectLineOfVerification">
    <error type="java.lang.Throwable" message="Method VerifySubjectLineOfVerification.test_027VerifyErrorMsgForIncorrectVeirficationCode()[pri:0, instance:com.edureka.registration.VerifySubjectLineOfVerification@e45f292] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method VerifySubjectLineOfVerification.test_027VerifyErrorMsgForIncorrectVeirficationCode()[pri:0, instance:com.edureka.registration.VerifySubjectLineOfVerification@e45f292] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </error>
  </testcase> <!-- test_027VerifyErrorMsgForIncorrectVeirficationCode -->
  <testcase name="test_031VerifyCompleteForgotPasswordFunctionality" time="0.000" classname="com.edureka.registration.VerifySubjectLineOfVerification">
    <error type="java.lang.Throwable" message="Method VerifySubjectLineOfVerification.test_031VerifyCompleteForgotPasswordFunctionality()[pri:0, instance:com.edureka.registration.VerifySubjectLineOfVerification@e45f292] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method VerifySubjectLineOfVerification.test_031VerifyCompleteForgotPasswordFunctionality()[pri:0, instance:com.edureka.registration.VerifySubjectLineOfVerification@e45f292] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </error>
  </testcase> <!-- test_031VerifyCompleteForgotPasswordFunctionality -->
  <testcase name="test_026VerifyCorrectVerificationCode" time="0.000" classname="com.edureka.registration.VerifySubjectLineOfVerification">
    <error type="java.lang.Throwable" message="Method VerifySubjectLineOfVerification.test_026VerifyCorrectVerificationCode()[pri:0, instance:com.edureka.registration.VerifySubjectLineOfVerification@e45f292] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method VerifySubjectLineOfVerification.test_026VerifyCorrectVerificationCode()[pri:0, instance:com.edureka.registration.VerifySubjectLineOfVerification@e45f292] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </error>
  </testcase> <!-- test_026VerifyCorrectVerificationCode -->
</testsuite> <!-- com.edureka.registration.VerifySubjectLineOfVerification -->
