<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="360LP048" name="com.edureka.leadProcess.SignInEnrollOnAnyCourse" tests="2" failures="1" timestamp="16 Sep 2016 13:38:26 GMT" time="206.145" errors="0">
  <testcase name="test_023EnrollOnAnyCourseLandingPage" time="62.491" classname="com.edureka.leadProcess.SignInEnrollOnAnyCourse">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.edureka.pages.DatabaseVerifications.dataVerificationInUserLeadTable(DatabaseVerifications.java:102)
	at com.edureka.pages.OrderSummaryPage.dataVerificationInUser_LeadsTable(OrderSummaryPage.java:193)
	at com.edureka.leadProcess.SignInEnrollOnAnyCourse.test_023EnrollOnAnyCourseLandingPage(SignInEnrollOnAnyCourse.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- test_023EnrollOnAnyCourseLandingPage -->
  <testcase name="test_014SignInEnrollOnAnyCourse" time="143.654" classname="com.edureka.leadProcess.SignInEnrollOnAnyCourse"/>
</testsuite> <!-- com.edureka.leadProcess.SignInEnrollOnAnyCourse -->
